### ISSUE TITLE
[About Us] Make detailed explanations of what our app is about

### ISSUE THREAD

**Issue by jokabe** [UHvibe/UHvibe#4]

**Comment by jokabe** [comment]
-Is these two really needed? 

-We can expand the landing page with more information instead of creating two new directories for two separate pages

**Comment by maiabe** [comment]
I think we should make the landing page broader since all the explanations there right now seems to be like catch-phrase-like (which is good)
So we still need our About Us page that users can refer to about detailed explanations of what the site is about.

**Comment by maiabe** [comment]
Task: Create "About Us" page with detailed explanations of what our app is about

**Comment by jokabe** [comment]
need to add more details (screen-shots of pages???)

**Comment by jokabe** [comment]
The general idea is hopefully there. Too many details might disinterest the visitor/user (So I tried to keep it precise and short). The design needs work (a lot of it).
